[[bin]]
name = "playground"

[package]
name = "playground"
version = "0.1.0"
authors = ["jeluard <julien@parity.io>"]
edition = "2018"

[dependencies]
log = "0.4.11"
env_logger = "0.8.1"
prometheus = "0.10.0"
hyper = "0.10" #Do not update
hyper-sync-rustls = "=0.3.0-rc.17"
rocket = "0.4.5"
rocket_contrib = { version = "0.4.5", features = ["json"] }
rocket_cors = "0.5.2"
rocket_oauth2 = { version = "0.4.1", features = ["hyper_sync_rustls_adapter"] }
rocket_prometheus = "0.7.0"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
serde_yaml = "0.8.13"
kube = "0.43.0"
k8s-openapi = { version = "0.10.0", default-features = false, features = ["v1_15"] }
tokio = {version = "0.2.22", features = ["macros"] }
time = "0.1" # Matches the version used by `cookie`