apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-deployment
  labels:
    app.kubernetes.io/component: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend-api
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      serviceAccountName: default-service-account
      containers:
      - name: backend-api
        image: paritytech/substrate-playground-backend-api
        ports:
        - containerPort: 80
        env:
          # See https://rocket.rs/v0.4/guide/configuration/
          - name: ROCKET_ENV
            value: "staging"
          - name: ROCKET_PORT
            value: "80"
          - name: ROCKET_LOG
            value: "normal"
          - name: ROCKET_ADDRESS
            value: "0.0.0.0"
          - name: ROCKET_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: rocket.secretKey
          - name: GITHUB_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: config
                key: github.clientId
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: secrets
                key: github.clientSecret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"