apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers 'Access-Control-Allow-credentials: true';
      more_set_headers 'Access-Control-Allow-Methods: PUT, GET, POST, PATCH, DELETE, OPTIONS';
      more_set_headers 'Access-Control-Allow-Origin: $http_origin';
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: backend-ui-service
          servicePort: ui-port
      - path: /grafana
        backend:
          serviceName: grafana-service
          servicePort: grafana-port
      - path: /api
        backend:
          serviceName: backend-api-service
          servicePort: api-port
