commonLabels:
    app.kubernetes.io/part-of: playground
    app.kubernetes.io/managed-by: kustomize

bases:
    - prometheus
    - grafana

resources:
    - backend-api-deployment.yaml
    - backend-api-service.yaml
    - backend-ui-deployment.yaml
    - backend-ui-service.yaml
    - cluster-role-binding.yaml
    - ingress.yaml
    - nginx.yaml
    - service-account.yaml