apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app.kubernetes.io/component: grafana
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      containers:
        - image: grafana/grafana
          name: grafana
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 2500Mi
            requests:
              cpu: 100m
              memory: 100Mi
         # volumeMounts:
         #   - name: config
         #     mountPath: "/etc/grafana/grafana.ini"
         #     subPath: grafana.ini
        #    - mountPath: /var/lib/grafana
         #     name: data
          env:
            # See https://rocket.rs/v0.4/guide/configuration/
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_SERVER_DOMAIN
              value: "playground-dev.substrate.test"
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
            - name: GF_SERVER_STATIC_ROOT_PATH
              value: "public"
      restartPolicy: Always
  #    volumes:
   #     - emptyDir: {}
  #        name: data
  #      - name: config
  #        configMap:
  #          name: grafana-config